'use strict';
// Bridge between the (remote) Chute page and the desktop shell. Keep it tiny.
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('chute', {
  platform: process.platform,
  notify: (p) => ipcRenderer.send('notify', { title: String(p && p.title || ''), body: String(p && p.body || ''), count: Number(p && p.count) || 0 }),
  clearUnread: () => ipcRenderer.send('clear-unread'),
  openSettings: () => ipcRenderer.send('open-settings'),
  chooseFiles: () => ipcRenderer.send('choose-files'),
  hide: () => ipcRenderer.send('hide'),
  togglePinned: () => ipcRenderer.invoke('toggle-pinned'),
  info: () => ipcRenderer.invoke('app-info'),
  takePassphrase: () => ipcRenderer.invoke('take-passphrase'),
  thumbnail: (f) => ipcRenderer.invoke('thumbnail', { name: String(f.name || ''), bytes: f.bytes }),
  quickLook: (f) => ipcRenderer.invoke('quick-look', { name: String(f.name || ''), bytes: f.bytes }),
  onDropFiles: (cb) => { ipcRenderer.on('drop-files', (_e, files) => cb(files)); },
  onDropText: (cb) => { ipcRenderer.on('drop-text', (_e, text) => cb(String(text))); },
  onShown: (cb) => { ipcRenderer.on('shown', () => cb()); },
  onPinned: (cb) => { ipcRenderer.on('pinned', (_e, v) => cb(!!v)); },
  onLock: (cb) => { ipcRenderer.on('lock', () => cb()); },
  onTrayDrag: (cb) => { ipcRenderer.on('tray-drag', (_e, on) => cb(!!on)); },
  dragInWindow: (on) => ipcRenderer.send('drag-in-window', !!on),
  stage: (f) => ipcRenderer.invoke('stage', { id: String(f.id), name: String(f.name || 'file'), bytes: f.bytes }),
  startDrag: (id) => ipcRenderer.send('start-drag', String(id)),
  unstage: (ids) => ipcRenderer.send('unstage', ids),
  serverInfo: (info) => ipcRenderer.send('server-info', { ttlHours: info.ttlHours, maxMB: info.maxMB }),
  connState: (st) => ipcRenderer.send('conn-state', String(st)),
  closeChute: () => ipcRenderer.send('close-chute'),
  quit: () => ipcRenderer.send('quit'),
  onShowSettings: (cb) => { ipcRenderer.on('show-settings', () => cb()); },
  onboarding: {
    get: () => ipcRenderer.invoke('settings:get'),
    save: (s) => ipcRenderer.invoke('settings:save', s),
    update: (patch) => ipcRenderer.invoke('settings:update', patch),
    copy: (text) => ipcRenderer.invoke('settings:copy', String(text)),
    probe: (url) => ipcRenderer.invoke('settings:probe', String(url || '')),
    finish: () => ipcRenderer.send('onboarding:finish'),
    startDiscovery: () => ipcRenderer.send('onboarding:discover', true),
    stopDiscovery: () => ipcRenderer.send('onboarding:discover', false),
    onDiscovered: (cb) => { ipcRenderer.on('discovered', (_e, svc) => cb(svc)); },
  },
  settings: {
    get: () => ipcRenderer.invoke('page-settings:get'),
    update: (patch) => ipcRenderer.invoke('page-settings:update', patch),
    chooseDir: () => ipcRenderer.invoke('page-settings:choose-dir'),
    revealPassphrase: () => ipcRenderer.invoke('page-settings:reveal-passphrase'),
    probe: () => ipcRenderer.invoke('page-settings:probe'),
    changePassphrase: (p) => ipcRenderer.invoke('page-settings:change-passphrase', String(p || '')),
  },
});
